### ISSUE TITLE
cil.li.oc package

### ISSUE THREAD

**Issue by zenith391** [AtomicScience/javoc#1]
To make programs running on [lukyt](https://github.com/zenith391/lukyt), and @TYKUHN2's OCJ compatible with your JVM. I suggest adding compatibility for the shared `cil.li.oc` package (maybe along your custom API if you plan to have one)

Javadoc: https://bwsecondary.ddns.net/jd/cil/li/oc/package-summary.html

**Comment by AtomicScience** [comment]
Will note, thank you!

**Comment by TYKUHN2** [comment]
I believe [lukyt](https://github.com/zenith391/lukyt) has mostly yielded defining the standard to me, but I'm more than willing to collaborate on creating it. OCJ is not yet public so the standard is far from set in stone.
